# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170503_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/images/default-profile.png', upload_to='profile_images'),
        ),
    ]
